#!/bin/bash

PROC='gunicorn jumpgate'

function is_running() {
	local __result=$1
	local __running=`pgrep -f "${PROC}"`
	eval $__result="'${__running:-0}'"
}

function start() {
	is_running running
	if [ "$running" == "0" ]; then
		echo "Starting jumpgate..."
		nohup gunicorn "jumpgate.wsgi:make_api()" --bind=0.0.0.0:5000 --timeout=600 --access-logfile=- -w 4 > /var/log/jumpgate.log 2>&1 &
	else
		echo "Jumpgate already running"
	fi
}

function stop() {
	is_running running
	if [ "$running" != "0" ]; then
		echo "Stopping jumpgate..."
		pkill -f "${PROC}"
	else
		echo "Jumpgate not running"
	fi
}

function restart() {
	stop
	start
}

function usage() {
	echo "Usage: jumpgate [stop|start|restart]"
}

case $1 in
'start')
	start
	;;
'stop')
	stop
	;;
'restart')
	restart
	;;
*)
	usage
	exit 1
	;;
esac

exit 0

